### ISSUE TITLE
border none: explanation

### ISSUE THREAD

**Issue by paceaux** [bjankord/stylelint-config-sass-guidelines#69]
Howdy, I'm trying to get to the bottom of why `border:none` is specifically disallowed: 
https://github.com/bjankord/stylelint-config-sass-guidelines/blob/master/src/.stylelintrc.json#L21

I see that this is based on [sass guidelines](https://sass-guidelin.es/#introduction), but the Sass Guidelines never recommend `border: 0` over `border: none` explicitly. 

The Sass Guidelines are based on [CSS Guidelines](https://cssguidelin.es/), but Harry Roberts never recommends this rule. 

The Sass Guidelines are also following [SCSS lint](https://github.com/sds/scss-lint), and SCSS Lint has this rule for `border:0`, but it, too, _never explains why_. 

SCSS-Lint has multiple examples of specifically surfacing an error for `border: none` but without explanation. 

So I'm making the rounds trying to determine why this rule exists and what benefit it serves. Could you provide an explanation?

**Comment by sarahdayan** [comment]
I believe [this is why](https://codepen.io/sarahdayan/pen/VwvKKMZ).

If you set a `border-style` to an element with `border: none` in a ruleset which selector has higher specificity, it overrides the fact that you set it to `none`. This breaks the [open/closed principle](https://cssguidelin.es/#the-openclosed-principle) .

**Comment by paceaux** [comment]
@sarahdayan I ended up publicly ranting about this issue on [twitter](https://twitter.com/Paceaux/status/1245058120977694722) where my conclusion similar to yours. It seems to lie within a use-case where, in the case of wanting to _return_ border to an element, more work must be done with `border: none` than `border-style: none` or `border-width: 0`;

I think my chief complaint here is that in all of my investigation, this isn't explained. I think if this rule persists in the guidelines, it should have a proper error message that explains why.

**Comment by bjankord** [comment]
@paceaux This lint rule came from [SCSS-Lint](https://github.com/sds/scss-lint/blob/master/lib/scss_lint/linter/README.md#borderzero). From their docs, "border: 0 and border: none are fundamentally different, as they are both shorthands. The intent of this linter is to enforce consistency, rather than define which is "better.""

That's how I view this lint rule as well, it primarily drives consistency, but it also helps with some more nuanced use-cases around border styling. I don't really have a good answer beyond that but I really like demo and explanation with regards to the [open/close principle](https://cssguidelin.es/#the-openclosed-principle) from @sarahdayan. 

I can updated the [readme section on this rule](https://github.com/bjankord/stylelint-config-sass-guidelines#declaration-property) to indicate that this rule is primarily about consistency.
